version: '3'

services:
  app:
    container_name: django
    build: ./django
    restart: always
    volumes:
     - ./django/code/:/code
    ports:
     - "8000:8000"
    command: python ./iyama/manage.py runserver 0.0.0.0:8000
    depends_on:           
     - db
  db:
    image: mysql:latest
    container_name: mysql
    build: ./mysql
    restart: always
    volumes:
     - ./mysql/data:/var/lib/mysql
    ports:
     - "3306:3306"
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'note'
      MYSQL_USER: 's2404'
      MYSQL_PASSWORD: 'admin24'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    expose:
      - "3306"
    privileged: true
